-- 向量处理任务表
CREATE TABLE IF NOT EXISTS `kb_vector_task` (
    `id`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_id`         VARCHAR(64)  NOT NULL COMMENT '任务ID（唯一标识，Java生成）',
    `doc_id`          BIGINT       NOT NULL COMMENT '文档ID',
    `kb_id`           BIGINT       NOT NULL COMMENT '知识库ID',
    `file_url`        VARCHAR(512) NOT NULL COMMENT '文件下载地址',
    `file_type`       VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '文件类型',
    `status`          TINYINT      NOT NULL DEFAULT 0 COMMENT '状态：0-待提交 1-处理中 2-已完成 3-失败 4-提交失败 5-超时',
    `progress`        INT          NOT NULL DEFAULT 0 COMMENT '进度（0-100）',
    `current_step`    VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '当前处理步骤',
    `chunk_count`     INT          NOT NULL DEFAULT 0 COMMENT '分块数量',
    `celery_task_id`  VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Celery任务ID',
    `error_msg`       VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '错误信息',
    `params`          VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '处理参数（JSON格式）',
    `creator`         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '创建者',
    `create_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater`         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    `update_time`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted`         BIT(1)       NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_task_id` (`task_id`),
    KEY `idx_doc_id` (`doc_id`),
    KEY `idx_kb_id` (`kb_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='向量处理任务表';
